"use client";
import Link from "next/link";
import { Bell, BellRing, Check, ChevronRight, Settings2, Sparkles, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Notice = { id: number; kind: string; title: string; body: string; href: string; created_at: string; read_at: string | null };
type Preferences = { notifyWorkout: boolean; notifyPr: boolean; notifyStreak: boolean; notifyRecovery: boolean };
const initialPrefs: Preferences = { notifyWorkout: true, notifyPr: true, notifyStreak: true, notifyRecovery: true };
function urlBase64ToUint8Array(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); const raw = atob((value + padding).replace(/-/g, "+").replace(/_/g, "/")); return Uint8Array.from([...raw].map(char => char.charCodeAt(0))); }

export default function NotificationCenter() {
  const [open, setOpen] = useState(false), [settings, setSettings] = useState(false), [busy, setBusy] = useState(false);
  const [enabled, setEnabled] = useState(false), [supported, setSupported] = useState(true), [notices, setNotices] = useState<Notice[]>([]);
  const [prefs, setPrefs] = useState(initialPrefs);
  const load = useCallback(async () => { try { const [push, list] = await Promise.all([fetch("/api/push").then(r => r.json()), fetch("/api/notifications").then(r => r.json())]); setEnabled(Boolean(push.subscription?.enabled) && Notification.permission === "granted"); setNotices(list.notifications ?? []); } catch {} }, []);
  useEffect(() => { setSupported("serviceWorker" in navigator && "PushManager" in window && "Notification" in window); load(); const timer = window.setInterval(() => { fetch("/api/push/sync", { method: "POST" }).then(() => load()).catch(() => null); }, 5 * 60 * 1000); return () => clearInterval(timer); }, [load]);
  async function enable() { setBusy(true); try { const permission = await Notification.requestPermission(); if (permission !== "granted") return; const registration = await navigator.serviceWorker.register("/sw.js"); const config = await fetch("/api/push").then(r => r.json()); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: urlBase64ToUint8Array(config.publicKey) }); await fetch("/api/push", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ subscription: subscription.toJSON() }) }); setEnabled(true); await load(); } finally { setBusy(false); } }
  async function disable() { setBusy(true); try { const registration = await navigator.serviceWorker.ready; const subscription = await registration.pushManager.getSubscription(); if (subscription) { await fetch("/api/push", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ endpoint: subscription.endpoint }) }); await subscription.unsubscribe(); } setEnabled(false); } finally { setBusy(false); } }
  async function savePrefs(next: Preferences) { setPrefs(next); await fetch("/api/push", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(next) }); }
  async function readAll() { await fetch("/api/notifications", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ all: true }) }); setNotices(current => current.map(item => ({ ...item, read_at: item.read_at ?? new Date().toISOString() }))); }
  const unread = notices.filter(item => !item.read_at).length;
  return <><button className="notification-head" onClick={() => setOpen(value => !value)} aria-label="Abrir notificações">{enabled ? <BellRing /> : <Bell />}{unread > 0 && <b>{unread > 9 ? "9+" : unread}</b>}<i className={enabled ? "online" : ""} /></button>{open && <aside className="notification-panel"><header><div><span><Sparkles /> COACH ALERTAS</span><h2>Notificações</h2><small>{enabled ? "Monitoramento ativo" : "Ative para receber insights"}</small></div><button onClick={() => setOpen(false)} aria-label="Fechar notificações"><X /></button></header>{!supported ? <div className="notification-callout"><Bell /><strong>Navegador não compatível</strong><p>Use Chrome, Edge ou instale o app no celular.</p></div> : !enabled ? <div className="notification-callout"><BellRing /><strong>Seu Coach pode te avisar.</strong><p>Receba conquistas, resumos e lembretes mesmo com o dashboard fechado.</p><button onClick={enable} disabled={busy}>{busy ? "Ativando…" : "Ativar notificações"}</button></div> : <><div className="notification-tools"><span><i /> Push ativado</span><button onClick={() => setSettings(value => !value)}><Settings2 /> Preferências</button></div>{settings && <div className="notification-settings">{([['notifyWorkout','Resumo pós-treino'],['notifyPr','Recordes pessoais'],['notifyStreak','Consistência e metas'],['notifyRecovery','Recuperação muscular']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input type="checkbox" checked={prefs[key]} onChange={event => savePrefs({ ...prefs, [key]: event.target.checked })} /></label>)}<button className="disable-push" onClick={disable} disabled={busy}>Desativar neste dispositivo</button></div>}<div className="notification-list">{notices.map(item => <Link href={item.href} className={item.read_at ? "" : "unread"} key={item.id}><span><Sparkles /></span><div><strong>{item.title}</strong><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString("pt-BR")}</small></div><ChevronRight /></Link>)}{!notices.length && <div className="notification-empty"><Check /><strong>Tudo em dia.</strong><p>Seus próximos insights aparecerão aqui.</p></div>}</div>{unread > 0 && <button className="read-all" onClick={readAll}><Check /> Marcar tudo como lido</button>}</>}</aside>}</>;
}
